server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/FredyYauri/proyecto-config.git
  application:
    name: config-server

